### ISSUE TITLE
Exception: 200-{"code":"100004","msg":"Order is in not cancelable state"}

### ISSUE THREAD

**Issue by aliforoghi72** [Kucoin/kucoin-futures-python-sdk#18]
How To Fix?

Traceback (most recent call last):
  File "C:\Users\sptpc\PycharmProjects\pythonProject2\Kucoin\kucoin-futures-main\ext1.py", line 30, in <module>
    o12=tradee.cancel_order(orderId=obb);print(o12)
  File "C:\Users\sptpc\PycharmProjects\pythonProject2\Kucoin\kucoin-futures-main\kucoin_futures\trade\trade.py", line 411, in cancel_order
    return self._request('DELETE', f'/api/v1/orders/{orderId}')
  File "C:\Users\sptpc\PycharmProjects\pythonProject2\Kucoin\kucoin-futures-main\kucoin_futures\base_request\base_request.py", line 95, in _request
    return self.check_response_data(response_data)
  File "C:\Users\sptpc\PycharmProjects\pythonProject2\Kucoin\kucoin-futures-main\kucoin_futures\base_request\base_request.py", line 112, in check_response_data
    raise Exception("{}-{}".format(response_data.status_code, response_data.text))
Exception: 200-{"code":"100004","msg":"Order is in not cancelable state"

**Comment by aliforoghi72** [comment]
How To Fix?

**Comment by ISAAC-XXYYZZ** [comment]
In cryptocurrency futures trading, there are several scenarios where an order may become non-cancelable:
Order Already Filled: If the order has been partially or fully filled, the filled portion cannot 
Order Triggered Special Conditions: If you set a conditional order (such as a stop-loss or take-profit order), and the condition has already been triggered, the order will be treated as a regular limit or market order by the market, and it cannot be canceled.
These scenarios can cause your order to become non-cancelable at a certain point, and specific rules may vary 
For more detailed information, please refer to our documentation: https://www.kucoin.com/support/26684247213849
